import { readFile } from "fs/promises";
import { join } from "path";
import Link from "next/link";
import { getTeamById } from "@/data/teams";
import EnhancedPickBadge from "./EnhancedPickBadge";
import PickTrackerButton from "./PickTrackerButton";

interface LivePick {
  fav: string;
  fav_id: number;
  home_id: number;
  away_id: number;
  home: string;
  away: string;
  prob: number;
  ml: string;
  ou_line: number;
  ou_lean: "over" | "under" | "push";
  result?: "W" | "L" | "no_result" | null;
  final_score?: string;
}

interface DayPicks {
  date: string;
  checked: boolean;
  picks: LivePick[];
}

interface PicksHistory {
  schema_version: number;
  start_date: string;
  record: { w: number; l: number };
  picks: DayPicks[];
}

function generatePickNarrative(pick: LivePick): string {
  const { fav, home, away, prob, ml, ou_line, ou_lean } = pick;
  const isHome = fav === home;
  const opponent = isHome ? away : home;
  const venue = isHome ? "at home" : "on the road";

  const probLevel = prob >= 70 ? "high" : prob >= 60 ? "moderate" : "slight";
  const mlNum = parseInt(ml);
  const mlDesc =
    mlNum < 0
      ? `favored at ${ml}`
      : `an underdog at +${Math.abs(mlNum)}`;

  let narrative = `StatScope's 9-factor model projected ${fav} with a ${prob.toFixed(0)}% chance of victory ${venue} against ${opponent}. `;

  if (prob >= 65) {
    narrative += `The ${probLevel} confidence rating reflects a meaningful statistical edge, driven by our integrated analysis of starting pitching quality, recent team form, and lineup strength. `;
  } else {
    narrative += `While the margin is slim, the model identified a statistically meaningful edge in this matchup based on starting pitcher comparison and recent form analysis. `;
  }

  narrative += `${fav} was ${mlDesc} according to the implied probability from the moneyline. `;

  if (ou_lean !== "push") {
    narrative += `The projected total of ${ou_line} runs suggested an ${ou_lean} tendency, based on estimated run-scoring potential from both lineups. `;
  } else {
    narrative += `With a projected total of ${ou_line} runs, the model did not indicate a strong lean in either direction on the total, suggesting balanced scoring potential from both offenses. `;
  }

  narrative += `This analysis is generated by StatScope's personal prediction model for informational and entertainment purposes only and should not be interpreted as betting advice.`;

  return narrative;
}

export default async function TodayPicksSection({
  date,
}: {
  date: string;
}) {
  try {
    const filePath = join(process.cwd(), "public/data/picks-history.json");
    const raw = await readFile(filePath, "utf-8");
    const history = JSON.parse(raw) as PicksHistory;

    let dayEntry = history.picks.find((d) => d.date === date);
    let isToday = true;

    if (!dayEntry || dayEntry.picks.length === 0) {
      dayEntry = history.picks.at(-1);
      isToday = false;
    }

    if (!dayEntry || dayEntry.picks.length === 0) {
      return null;
    }

    const record = history.record;
    const picks = dayEntry.picks;

    return (
      <section className="mb-8">
        {/* Header */}
        <div className="mb-6">
          <div className="flex items-center gap-3 mb-2">
            <span className="inline-block w-1 h-6 bg-blue-500 rounded-full" />
            <h2 className="text-2xl font-bold text-slate-800">
              {isToday ? "Today's" : "Latest"} Model Analysis
            </h2>
            <span className="text-xs font-semibold text-blue-600 bg-blue-50 px-2.5 py-1 rounded-full">
              v2.2
            </span>
          </div>
          <p className="text-sm text-slate-600 ml-4">
            {dayEntry.date}{isToday ? "" : " (latest available)"}
          </p>
        </div>

        {/* Fallback notice */}
        {!isToday && (
          <div className="mb-6 rounded-xl bg-amber-50 border border-amber-200 p-4">
            <p className="text-xs text-amber-700">
              📅 Showing picks from <strong>{dayEntry.date}</strong> — no picks
              have been posted yet for today. Check back before game time for the
              latest analysis.
            </p>
          </div>
        )}

        {/* Record summary */}
        <div className="mb-6 grid grid-cols-2 gap-4 sm:grid-cols-4">
          <div className="rounded-xl bg-slate-50 p-4">
            <p className="text-xs text-slate-500 font-semibold">Record</p>
            <p className="text-lg font-extrabold text-slate-800">
              {record.w}-{record.l}
            </p>
          </div>
          <div className="rounded-xl bg-slate-50 p-4">
            <p className="text-xs text-slate-500 font-semibold">Win Rate</p>
            <p className="text-lg font-extrabold text-slate-800">
              {record.w + record.l > 0
                ? ((record.w / (record.w + record.l)) * 100).toFixed(1)
                : "—"}
              %
            </p>
          </div>
          <div className="rounded-xl bg-slate-50 p-4 sm:col-span-2">
            <p className="text-xs text-slate-500 font-semibold">
              Total Picks Available
            </p>
            <p className="text-lg font-extrabold text-slate-800">
              {history.picks.reduce((sum, d) => sum + d.picks.length, 0)}
            </p>
          </div>
        </div>

        {/* Picks grid */}
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3 mb-6">
          {picks.map((pick, idx) => {
            const homeTeam = getTeamById(pick.home_id);
            const awayTeam = getTeamById(pick.away_id);
            const narrative = generatePickNarrative(pick);

            // Probability badge color
            let probBgColor = "bg-gray-100";
            let probTextColor = "text-slate-600";
            if (pick.prob >= 70) {
              probBgColor = "bg-emerald-50";
              probTextColor = "text-emerald-700";
            } else if (pick.prob >= 60) {
              probBgColor = "bg-amber-50";
              probTextColor = "text-amber-700";
            }

            // Result badge
            let resultBadge = null;
            if (pick.result === "W") {
              resultBadge = (
                <span className="inline-block px-2 py-1 rounded-full text-xs font-semibold bg-emerald-50 text-emerald-700">
                  ✓ W
                </span>
              );
            } else if (pick.result === "L") {
              resultBadge = (
                <span className="inline-block px-2 py-1 rounded-full text-xs font-semibold bg-red-50 text-red-700">
                  ✗ L
                </span>
              );
            }

            return (
              <div
                key={idx}
                className="rounded-2xl bg-white shadow-sm ring-1 ring-slate-200/60 p-5 flex flex-col"
              >
                {/* Matchup header */}
                <div className="mb-4 flex items-center justify-between">
                  <div className="flex items-center gap-2 text-sm font-semibold">
                    <span
                      className="w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold text-white"
                      style={{
                        backgroundColor: awayTeam?.colorPrimary || "#6B7280",
                      }}
                      title={awayTeam?.name}
                    >
                      {awayTeam?.abbreviation || "?"}
                    </span>
                    <span className="text-slate-500">@</span>
                    <span
                      className="w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold text-white"
                      style={{
                        backgroundColor: homeTeam?.colorPrimary || "#6B7280",
                      }}
                      title={homeTeam?.name}
                    >
                      {homeTeam?.abbreviation || "?"}
                    </span>
                  </div>
                  {resultBadge && resultBadge}
                </div>

                {/* Matchup names */}
                <p className="text-xs text-slate-500 mb-3 leading-snug">
                  <span className="font-semibold text-slate-700">
                    {pick.away}
                  </span>{" "}
                  @ <span className="font-semibold text-slate-700">{pick.home}</span>
                </p>

                {/* Enhanced badge */}
                <div className="mb-3">
                  <EnhancedPickBadge
                    gameId={`${awayTeam?.abbreviation || "?"}@${homeTeam?.abbreviation || "?"}`}
                    baseProb={pick.prob}
                  />
                </div>

                {/* Probability badge */}
                <div className={`rounded-lg ${probBgColor} p-3 mb-4`}>
                  <div className={`text-xl font-extrabold ${probTextColor}`}>
                    {pick.prob.toFixed(1)}%
                  </div>
                  <div className="text-xs text-slate-600 mt-1">
                    {pick.prob >= 70
                      ? "High Confidence"
                      : pick.prob >= 60
                      ? "Moderate Confidence"
                      : "Slight Edge"}
                  </div>
                </div>

                {/* Odds chips */}
                <div className="flex gap-2 mb-4 flex-wrap">
                  <span className="text-xs bg-slate-100 text-slate-700 px-2.5 py-1 rounded-full">
                    ML: {pick.ml}
                  </span>
                  <span className="text-xs bg-slate-100 text-slate-700 px-2.5 py-1 rounded-full">
                    O/U: {pick.ou_line}
                  </span>
                </div>

                {/* Narrative */}
                <p className="text-sm text-slate-600 leading-7 mb-4 flex-grow">
                  {narrative}
                </p>

                {/* View game link + Track button */}
                <div className="flex items-center justify-between">
                  <Link
                    href={`/?date=${pick.home_id}`}
                    className="text-xs text-blue-600 hover:underline font-semibold"
                  >
                    View game →
                  </Link>
                  <PickTrackerButton
                    date={dayEntry.date}
                    fav={pick.fav}
                    fav_id={pick.fav_id}
                    home_id={pick.home_id}
                    away_id={pick.away_id}
                    home={pick.home}
                    away={pick.away}
                    prob={pick.prob}
                    ml={pick.ml}
                    ou_line={pick.ou_line}
                    ou_lean={pick.ou_lean}
                  />
                </div>
              </div>
            );
          })}
        </div>

        {/* Footer */}
        <div className="rounded-xl bg-slate-50 border border-slate-200 p-4">
          <p className="text-xs text-slate-500 leading-relaxed mb-3">
            <strong>Disclaimer:</strong> StatScope predictions are generated by
            a personal 9-factor machine learning model for informational and
            entertainment purposes only. These predictions are not betting advice
            and do not guarantee any outcome. Past performance does not indicate
            future results. Always gamble responsibly.
          </p>
          <Link href="/track" className="text-xs text-blue-600 hover:underline font-semibold">
            View full model track record & calibration →
          </Link>
        </div>
      </section>
    );
  } catch {
    return null;
  }
}
